### ISSUE TITLE
CSS Text Manipulation Mutation

### ISSUE THREAD

**Issue by mrv1k** [mrv1k/bracketless#8]
I'm hiding text is by setting its font-size to 0
However,  that overrides default font size so that it can not be inherited
To reverse that I have to use a hard set value (1 rem in this case)

Desired:
A way to hide text without size mutation.

"display: none" gets suggested a lot but that will not fix the issue and instead move it to display land
One solution is to store & restore font size via JS but I want to try to do it with CSS before

**Comment by gatezh** [comment]
Is it here?
bracketless/core/css/action.css
What's the problem with `font-size: inherit` instead of `1rem`?

**Comment by mrv1k** [comment]
Font size “inherit” inherits font size 0. That’s the problem.

**Comment by mrv1k** [comment]
Project archived.
